apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    application: nginx
    stage: dev
  template:
    metadata:
      labels:
        application: nginx
        stage: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
